version: 2
jobs:
  build: 
    docker:
        - image: microsoft/dotnet:sdk
        - image: docker:17.05.0-ce-git
    steps:
      - checkout 
      - setup_remote_docker
      - run:
          name: Restore Nuget
          command: dotnet restore 
      - run:
          name: Build Project
          command: dotnet build 
      - deploy:
          command: |
             chmod +x ./deploy.sh
             sh ./deploy.sh